### ISSUE TITLE
Add scaffolding workflow

### ISSUE THREAD

**Issue by demersdesigns** [ericwbailey/boilerplate#4]
# Add scaffolding workflow

## Expected behavior
Allow the user to run through a process to add global project variables to the project.

## Proposal:
Enhance the current find/replace workflow with a generator using the [Slush JS](http://slushjs.github.io/) tool.

**Comment by ericwbailey** [comment]
This is a great idea 👍

**Comment by demersdesigns** [comment]
Slush JS ended up being overkill. I was able to accomplish what I needed with `gulp-token-replace` and `inquirer`.

**Comment by ericwbailey** [comment]
Hey, just a head's up: I'm going to temporarily revert to make sure other tweaks get in.

**Comment by demersdesigns** [comment]
Sounds good! Thanks for letting me know. :-)

**Comment by ericwbailey** [comment]
Added a Makefile that'll sorta take care of this, so I'm calling it closed.
